### ISSUE TITLE
Add paper reference

### ISSUE THREAD

**Issue by robmarkcole** [Levantespot/UDA_for_RS#1]
Appears to be https://arxiv.org/abs/2208.07722 ?

**Comment by Levantespot** [comment]
Thank you for your interest. The paper is undergoing a second peer review. In the meantime, we have prepared a preprint and will post a link to it soon.

**Comment by Levantespot** [comment]
> Appears to be https://arxiv.org/abs/2208.07722 ?

Not this article.

**Comment by Levantespot** [comment]
We have added paper reference.
