### ISSUE TITLE
自训练相关的问题

### ISSUE THREAD

**Issue by ljx97** [Levantespot/UDA_for_RS#2]
您好，您的工作十分有趣，并且很感谢您公开代码。您在论文中写到：在自训练无监督域自适应框架中，学生模型会首先以有监督的方式使用源域数据被训练。我想请问一下，这个过程是在这个框架中进行的吗？这部分的config您是没有公开吗？

**Comment by ljx97** [comment]
在您公开的模型链接中显示，您加载的模型是mit_b5.pth，这很令我疑惑，期待您的回复

**Comment by Levantespot** [comment]
首先，感谢您的关注。

针对第一个问题，本文的自训练框架的整体训练流程可以查阅 `mmseg/models/uda/dacs.py` 文件，其中包含了源域和目标域的两部分训练过程。且训练过程所有超参都由 `configs/*` 文件夹中的对应配置文件指定，因此是公开的。

针对第二个问题，本文研究的是一种自训练域自适应策略，不涉及到语义分割模型架构的具体研究，因此使用学业界已有模型。而关于模型的选择理由请参考论文 3.2 节的模型架构部分。

谢谢。

**Comment by ljx97** [comment]
感谢您的回答！我不知道我理解的对不对：您使用的是在imagenet-1k上训练的mit_b5.pth作为教师模型去生成目标域的伪标签的嘛？

**Comment by ljx97** [comment]
不好意思，我刚开始关注这方面的研究，实在是不太懂呀。

**Comment by Levantespot** [comment]
>您使用的是在imagenet-1k上训练的mit_b5.pth作为教师模型去生成目标域的伪标签的嘛？

教师模型和学生模型都是使用的在 imagenet-1k 上预训练好的模型进行初始化的，后续教师模型和学生模型的参数都会进行迭代更新，因此只有在第一次生成伪标签时可以这么理解。

**Comment by ljx97** [comment]
好的！谢谢您！我确实在复现的时候遇到了一些问题，损失变成了none，您知道是什么原因嘛？
![image](https://github.com/Levantespot/UDA_for_RS/assets/73821833/c3228076-43b9-4951-88c1-7aaf1720de5f)

**Comment by Levantespot** [comment]
可能是出现了除数为 0 的计算表达式。

**Comment by ljx97** [comment]
好的，谢谢

**Comment by jiuyuzhang** [comment]
你好，请问你的这个问题解决了吗，能否给我参考一下当时的参数设置呢，我这边是遇到了一个其他的问题
